[package]
name = "zingo-netutils"
version = "4.0.0"
description = "network utility crate"
authors = ["zingo@zingolabs.org"]
edition.workspace = true
repository = "https://github.com/zingolabs/zingo-common"
homepage = "https://github.com/zingolabs/zingo-common"
license = "MIT"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
http.workspace = true
thiserror.workspace = true
tokio-rustls.workspace = true
tonic.workspace = true
lightwallet-protocol.workspace = true
tokio-stream = { workspace = true, optional = true }
zcash_client_backend = { workspace = true, optional = true }
nym-sdk = { workspace = true, optional = true }
nym-http-api-client = { workspace = true, optional = true }
nym-validator-client = { workspace = true, optional = true }
tokio-socks = { workspace = true, optional = true }
tower = { workspace = true, optional = true }
hyper-util = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
webpki-roots = { workspace = true, optional = true }

[features]
globally-public-transparent = ["dep:tokio-stream"]
ping-very-insecure = []
back_compatible = ["dep:zcash_client_backend"]
nym = [
    "dep:nym-sdk",
    "dep:nym-http-api-client",
    "dep:nym-validator-client",
    "dep:tokio-socks",
    "dep:tower",
    "dep:hyper-util",
    "dep:tokio",
    "dep:webpki-roots",
]

[dev-dependencies]
tokio-stream.workspace = true
hyper-rustls.workspace = true
hyper-util.workspace = true
hyper.workspace = true
rustls-pemfile.workspace = true
tokio.workspace = true
http-body-util.workspace = true
x509-parser.workspace = true
